url: 'https://kernelpanic.studio/'
baseurl: ''
title: 'Mateusz Cabizza is Kernel Panic Studio'
description:
  en: 'Personal portfolio of a designer, webdev and 3D artist. Available for hire!'
  it: ''
image:
  url: '/assets/images/default.webp'
  alt:
    en: 'Kernel Panic Studio logo'
    it: 'Il logo di Kernel Panic Studio'

plugins:
  - jekyll-postcss
  - jekyll-polyglot
  - ./_plugins/portfolio-generator.rb

#polyglot
languages: ["en", "it"]
default_lang: "en"
exclude_from_localization: ["assets", "css", "js", "CNAME", "README.md", "package-lock.json"]
path: ":lang/:url"
parallel_localization: false

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - node_modules
  - Gemfile

# portfolio generator
portfolio_dir: "projects"
skip_related_projects: true