url: 'https://icodeonsunday.github.io/'
baseurl: ''
title: 'Mateusz Cabizza is Kernel Panic Studio'
destination: site


plugins:
  - jekyll-postcss
  - jekyll-seo-tag

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - node_modules
  - Gemfile

portfolio_dir: "projects"
skip_related_projects: true