url: 'https://icodeonsunday.github.io/'
baseurl: '/kpstudio/'
title: 'Mateusz Cabizza is Kernel Panic Studio'

plugins:
  - jekyll-seo-tag

postcss:
  cache: false

exclude:
  - package.jso
  - postcss.config.js
  - tailwind.config.js
  - node_modules
  - Gemfile

portfolio_dir: "projects"
skip_related_projects: true